import type { DemoProblemSet } from "./types";

/** UI-only cards. These describe sample catalogue metadata, not exam questions. */
export const demoProblemSets: DemoProblemSet[] = [
  {
    id: "demo-mock-exam-01",
    slug: "bo-de-thi-thu-minh-hoa-a",
    title: "Đề thi thử minh họa A",
    description: "Bản xem trước một bộ đề tổng hợp, tạo riêng để thử giao diện MathPath.",
    language: "vi",
    category: "mock_exam",
    difficulty: "mixed",
    topicNames: ["Tổng hợp"],
    questionCount: 22,
    timingMode: "countdown",
    timeLimitMinutes: 90,
    estimatedDurationMinutes: null,
    examYear: 2027,
    examOrganization: "Bộ dữ liệu minh họa",
    examSession: "Mẫu A",
    publishedAt: "2026-10-01T08:00:00.000Z",
    isMock: true,
  },
  {
    id: "demo-topic-functions-01",
    slug: "ham-so-minh-hoa-a",
    title: "Hàm số: thử sức bản minh họa",
    description: "Thẻ mẫu cho dạng ôn theo chuyên đề; hiện chưa có câu hỏi thật bên trong.",
    language: "vi",
    category: "topic_review",
    difficulty: "medium",
    topicNames: ["Hàm số", "Đạo hàm"],
    questionCount: 20,
    timingMode: "elapsed",
    timeLimitMinutes: null,
    estimatedDurationMinutes: 35,
    examYear: null,
    examOrganization: null,
    examSession: null,
    publishedAt: "2026-10-02T08:00:00.000Z",
    isMock: true,
  },
  {
    id: "demo-chapter-functions-01",
    slug: "chuong-ham-so-minh-hoa",
    title: "Chương Hàm số: xem trước",
    description: "Ví dụ giao diện cho bộ ôn tập theo chương, không phải tài liệu nguồn.",
    language: "vi",
    category: "chapter_review",
    difficulty: "easy",
    topicNames: ["Hàm số"],
    questionCount: 12,
    timingMode: "elapsed",
    timeLimitMinutes: null,
    estimatedDurationMinutes: 25,
    examYear: null,
    examOrganization: null,
    examSession: null,
    publishedAt: "2026-09-28T08:00:00.000Z",
    isMock: true,
  },
  {
    id: "demo-comprehensive-01",
    slug: "luyen-tap-tong-hop-minh-hoa",
    title: "Luyện tập tổng hợp: bản demo",
    description: "Thẻ minh họa cho bộ câu hỏi trộn nhiều chủ đề Toán THPT.",
    language: "vi",
    category: "comprehensive",
    difficulty: "mixed",
    topicNames: ["Đại số", "Hình học", "Xác suất"],
    questionCount: 30,
    timingMode: "elapsed",
    timeLimitMinutes: null,
    estimatedDurationMinutes: 60,
    examYear: null,
    examOrganization: null,
    examSession: null,
    publishedAt: "2026-09-24T08:00:00.000Z",
    isMock: true,
  },
  {
    id: "demo-topic-functions-02",
    slug: "ung-dung-dao-ham-minh-hoa",
    title: "Ứng dụng đạo hàm: bản minh họa",
    description: "Ví dụ thẻ chủ đề nâng cao dùng để kiểm tra tìm kiếm và bộ lọc.",
    language: "vi",
    category: "topic_review",
    difficulty: "hard",
    topicNames: ["Hàm số", "Đạo hàm", "Giá trị lớn nhất"],
    questionCount: 8,
    timingMode: "elapsed",
    timeLimitMinutes: null,
    estimatedDurationMinutes: 20,
    examYear: null,
    examOrganization: null,
    examSession: null,
    publishedAt: "2026-09-20T08:00:00.000Z",
    isMock: true,
  },
  {
    id: "demo-chapter-integrals-01",
    slug: "tich-phan-minh-hoa",
    title: "Chương Tích phân: bản minh họa",
    description: "Thẻ dữ liệu giả lập để kiểm tra bộ lọc theo chương học.",
    language: "vi",
    category: "chapter_review",
    difficulty: "medium",
    topicNames: ["Tích phân"],
    questionCount: 14,
    timingMode: "elapsed",
    timeLimitMinutes: null,
    estimatedDurationMinutes: 30,
    examYear: null,
    examOrganization: null,
    examSession: null,
    publishedAt: "2026-09-18T08:00:00.000Z",
    isMock: true,
  },
];
